name: Update README

on:
    push:
        branches:
            - main

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install music-metadata

            - name: Run script to update README
              run: node scripts/update_readme.mjs

            - name: Commit and push changes
              run: |
                  git config --global user.name 'ClaytonTDM'
                  git config --global user.email 'claytontdm@gmail.com'
                  git add README.md
                  git commit -m 'Update README with file structure'
                  git push
              env:
                  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}