name: List Files

on:
  push:
    branches: [ main ]

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: List files
      run: |
        ls -R > file_list.txt
        sed -i 's/^\.\//:/' file_list.txt
    - name: Update README
      uses: peaceiris/actions-readme@v2
      with:
        template: auto
        toc_levels: 3
        auto_update: true
      env:
        README_CONTENTS: |
          # File List
          
          ```
          $(cat file_list.txt)
          ```
