name: Unrar and Commit

on:
  push:
    branches:
      - main
    
jobs:
  unrar-and-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Unrar Files
      run: |
        sudo apt-get update
        sudo apt-get install -y unrar
        cd "Super Hexagon EP"
        unrar x -y "*.part1.rar"
        rm "*.part*.rar"
    
    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Unrar and commit Super Hexagon EP"
    
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: main
        directory: .
