on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

name: TOC Generator

jobs:
  toc:
    name: TOC Generator
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          IGNORE_WARNING: 'true'
      - uses: technote-space/toc-generator@gh-actions
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
