name: Generate Table of Contents

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/toc-generator@v4
        with:
          path: './'
      - name: Commit changes
        run: |
          git config --global user.email "claytontdm@gmail.com"
          git config --global user.name "ClaytonTDM"
          git add .
          git commit -m "update table of contents"
          git push
