on:
  push:
    branches:
      - main

name: TOC Generator

jobs:
  toc:
    name: TOC Generator
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/toc-generator@gh-actions
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
